@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 08 01:26:23 -0800 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim SR_latch_tb_behav -key {Behavioral:sim_1:Functional:SR_latch_tb} -tclbatch SR_latch_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_1/SR_latch_tb_behav.wcfg -log simulate.log"
call xsim  SR_latch_tb_behav -key {Behavioral:sim_1:Functional:SR_latch_tb} -tclbatch SR_latch_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_1/SR_latch_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
