@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 10 19:48:34 -0800 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim shift_register_1bit_delay_tb_behav -key {Behavioral:sim_1:Functional:shift_register_1bit_delay_tb} -tclbatch shift_register_1bit_delay_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab6/lab6_1_3/shift_register_1bit_delay_tb_behav.wcfg -log simulate.log"
call xsim  shift_register_1bit_delay_tb_behav -key {Behavioral:sim_1:Functional:shift_register_1bit_delay_tb} -tclbatch shift_register_1bit_delay_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab6/lab6_1_3/shift_register_1bit_delay_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
