set_property SRC_FILE_INFO {cfile:C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab6/lab6_1_2/Basys3_Master.xdc rfile:../../../../lab6_1_2/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {shiftin}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {shiftout}]
