@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 09 21:39:08 -0800 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim D_flipflop_with_synch_reset_tb_behav -key {Behavioral:sim_1:Functional:D_flipflop_with_synch_reset_tb} -tclbatch D_flipflop_with_synch_reset_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_2_3/D_flipflop_with_synch_reset_tb_behav.wcfg -log simulate.log"
call xsim  D_flipflop_with_synch_reset_tb_behav -key {Behavioral:sim_1:Functional:D_flipflop_with_synch_reset_tb} -tclbatch D_flipflop_with_synch_reset_tb.tcl -view C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_2_3/D_flipflop_with_synch_reset_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
