webtalk_init -webtalk_dir C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_2/lab5_1_2.sim/sim_1/behav/xsim/xsim.dir/gated_SR_latch_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  9 16:43:25 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212401897_0_0_249" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3c6a0502-6a03-4ffd-8c3b-92bc9e8f6620" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "64238d638c2a44c48071fa0c6e21860c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3767743297 -regid "212401897_0_0_249" -xml C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_2/lab5_1_2.sim/sim_1/behav/xsim/xsim.dir/gated_SR_latch_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_2/lab5_1_2.sim/sim_1/behav/xsim/xsim.dir/gated_SR_latch_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/yvvan/Documents/Research/Vivado_Verilog_Tutorial/lab5/lab5_1_2/lab5_1_2.sim/sim_1/behav/xsim/xsim.dir/gated_SR_latch_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
